---
- name: copy to remote
  become: true
  copy:
        src: artifact.tar.gz
        dest: ~

- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Extract 'artifact.tar.gz' 
  ansible.builtin.unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: Executing node
  become: true
  shell: |   
    cd ~/backend
    pm2 stop default
    pm2 start npm --name "backend" -- start
